---
  - name: "The remote environment"
    shell: env
  - name: "Extract Artifact"
    become: yes
    unarchive:
        src: files/artifact.tar.gz
        dest: /home/ubuntu
  - name: "start server"
    become: true
    shell: | 
      cd /home/ubuntu
      npm install
      pm2 stop default
      sudo pm2 start npm -- start
             

